# Generated by Django 2.2.3 on 2019-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='submit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
